"""add english translation fields

Revision ID: b8f849e4b7ba
Revises: d27fe454ab6c
Create Date: 2026-09-29 00:34:34.398462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8f849e4b7ba'
down_revision: Union[str, None] = 'd27fe454ab6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_variants', sa.Column('name_en', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('name_en', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('description_en', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'description_en')
    op.drop_column('products', 'name_en')
    op.drop_column('product_variants', 'name_en')
    # ### end Alembic commands ###
